### PR TITLE
Adds support for internationalization and localization via i18next (#548 redux)

### PR DESCRIPTION
**Pull request by mattmcguirk**
See #548. This pull request also properly places locales in the build/mirador directory and configures i18next to look for them there.

### CODE REVIEW

**Comment by rsinghal** [comment]
Cool, this is working on my dev server now!
Can you take a look at #553 as well?

**Comment by mattmcguirk** [comment]
This should resolve #553 as well; some additional key/value pairs have been
added to the translation.json files.

On Mon, Jun 15, 2015 at 2:26 PM, rsinghal <notifications@github.com> wrote:

> Cool, this is working on my dev server now!
> Can you take a look at #553 <https://github.com/IIIF/mirador/issues/553>
> as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/pull/564#issuecomment-112161818>.
>



-- 


Matt McGuirk
matt.mcguirk@gmail.com
(646) 226-9545

**Comment by azaroth42** [comment]
:-1: if I understand what is being proposed.

The translation of "label"s and "value"s from the manifest can take place *in* the manifest with multiple languages. It doesn't need to be, and should not be, handled by supplying translations on a client by client basis.  The i18n code should look at the options in the manifest and select the one that matches the user's preferences.

Fixtures are available from e-codices, e.g.:
    http://sr-svx-93.unifr.ch/metadata/iiif/bbb-0162/manifest.json

**Comment by mattmcguirk** [comment]
Agreed, that is a better solution. Thank you for clarifying that.

On Tue, Jun 16, 2015 at 10:50 AM, Rob Sanderson <notifications@github.com>
wrote:

> [image: :-1:] if I understand what is being proposed.
>
> The translation of "label"s and "value"s from the manifest can take place
> *in* the manifest with multiple languages. It doesn't need to be, and
> should not be, handled by supplying translations on a client by client
> basis. The i18n code should look at the options in the manifest and select
> the one that matches the user's preferences.
>
> Fixtures are available from e-codices, e.g.:
> http://sr-svx-93.unifr.ch/metadata/iiif/bbb-0162/manifest.json
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/pull/564#issuecomment-112458464>.
>



-- 


Matt McGuirk
matt.mcguirk@gmail.com
(646) 226-9545

**Comment by rsinghal** [comment]
Maybe @regisrob can give some more detail?  I thought he just wanted the labels that are displayed in that metadata overlay [template] (https://github.com/IIIF/mirador/blob/master/js/src/widgets/metadataView.js#L242) to change.

**Comment by azaroth42** [comment]
:+1: to translations for those (client supplied) labels.

In the metadata code:
* label
* description
* related
* seeAlso
* within

In the template:
* Details
* Rights
* Links


On Tue, Jun 16, 2015 at 8:07 AM, rsinghal <notifications@github.com> wrote:

> Maybe @regisrob <https://github.com/regisrob> can give some more detail?
> I thought he just wanted the labels that are displayed in that metadata
> overlay template
> <https://github.com/IIIF/mirador/blob/master/js/src/widgets/metadataView.js#L242>
> to change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/pull/564#issuecomment-112463979>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by regisrob** [comment]
Completely agree with Rob, this is THE expected solution. I was misled by the fact that i18next allows that kind of translation and nobody (except e-codices as far as I know) has multilingual metadata pairs. We should definitely do that for the forthcoming BnF/Biblissima manifests

**Comment by regisrob** [comment]
So as for the translation of metadata labels, we should have in the manifest:
<pre>
"metadata":[
  {
    "label": [
    {
      "@value":"Location",
      "@language":"en"
    },
    {
      "@value":"Localisation",
      "@language":"fr"
    }
    ],
    "value":"Bern"
  }
]
</pre>

Correct?

**Comment by mattmcguirk** [comment]
This should be ready to be merged. The code that translated the metadata on the client side without consulting the manifest has been removed.

**Comment by rsinghal** [comment]
Cool thanks, will manually merge everything back in.

**Comment by rsinghal** [comment]
@mattmcguirk can you double check that everything looks good in https://github.com/IIIF/mirador/tree/pr564-manual?  It is working for and everything seems right, but you know the code better than I do.  Thanks!

**Pull request closed without merging**
