### PR TITLE
Adaption of the thumbnail

### PR DESCRIPTION
**Pull request by fe-kre**
Problem was a thumbnail that would be bigger than a usual screen.

I set up fixed values as limits. If the aspect ratio exceeds one limit, than calculate the width or height again with a correction variable. After that point, recalculate the aspect ratio and the new width.

Because of quality reasons for the thumbnail, I set the width to a fixed value.

### CODE REVIEW

**Comment by rsinghal** [comment]
Thanks @fe-kre.  Can you include an example manifest that caused the problem originally?

**Comment by fe-kre** [comment]
http://iiif.ub.uni-leipzig.de/0000000001/manifest.json is an example manifest for our problem.

**Comment by rsinghal** [comment]
@fe-kre The code changes are messing up the thumbnails for existing images.

Before:
screen shot 2016-04-04 at 11 51 14 am

After:
screen shot 2016-04-04 at 11 51 27 am

**Comment by rsinghal** [comment]
@fe-kre Please fix and reopen the PR when you are ready.

**Comment by fe-kre** [comment]
We have taken a new approach to our problem and have resolved it with the help of css properties.

I set up a new div around 'preview-images' and gave him the properties position: absolute and display: inline-flex. So our outsized thumbnail shows up.

Hopefully this is an acceptable way to deal with our problem.

**Pull request closed without merging**
