### PR TITLE
added singular item

### PR DESCRIPTION
**Pull request by rsinghal**

### CODE REVIEW

**Comment by rsinghal** [comment]
@regisrob @jbhoward-dublin @netsensei I added the translation for singular "item".  Can you please confirm that I added the correct translation for any language you know?  Thanks!

**Comment by netsensei** [comment]
Dutch: okay for me.

**Comment by regisrob** [comment]
French: :+1:

**Comment by jbhoward-dublin** [comment]
Irish: yes, that's right

On Wed, Dec 16, 2015 at 5:28 PM, Rashmi Singhal <notifications@github.com>
wrote:

> @regisrob <https://github.com/regisrob> @jbhoward-dublin
> <https://github.com/jbhoward-dublin> @netsensei
> <https://github.com/netsensei> I added the translation for singular
> "item". Can you please confirm that I added the correct translation for any
> language you know? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/pull/725#issuecomment-165183870>.
>



-- 
John B Howard
Beechgrove
Glenageary Road Lower
Glenageary
Co. Dublin
Ireland
Skype:John.B.Howard

**Pull request merged**
