### PR TITLE
Mark all annotation's shapes as 'active' when hovering one of them

### PR DESCRIPTION
**Pull request by radpet**
Mark all annotation's shapes as 'active' when hovering one of them

You can configure hover color by:

'drawingToolsSettings': { 'hoverColor': 'yellow' },

color can be anything from http://paperjs.org/reference/color/

### CODE REVIEW

**Comment by radpet** [comment]
After we merge the previous two pr I will rebase on top of annotation-work

**Comment by radpet** [comment]
@rsinghal  
I will look for a fix to display annotations from http://dms-data.stanford.edu/data/manifests/Stanford/ege1/manifest.json
as a part of this pr

**Comment by rsinghal** [comment]
@radpet sounds good

**Comment by radpet** [comment]
@rsinghal I see no annotations from http://dms-data.stanford.edu/data/manifests/Stanford/ege1/manifest.json
what should be my configuration like?

**Comment by rsinghal** [comment]
As long as you have the annotations button available to you, it should pull them.  In window.js, the code looks here: https://github.com/IIIF/mirador/blob/annotation-work/js/src/workspaces/window.js#L768.  

The manifest has snippets like this:
```
otherContent: [
{
@id: "http://dms-data.stanford.edu/data/manifests/Stanford/kq131cs7229/list/text-f8r.json",
@type: "sc:AnnotationList"
}
]
```
which point to manifest level annotations and if you follow that path, you will see basic rectangular annotations, using xywh.  `window.js` merges manifest annotations and annotations from a database into a single array so they can all be displayed side by side.  I recommend switching to `release2.1` from this repo to confirm you can see them, like this:

screen shot 2016-06-27 at 10 55 11 am

**Comment by radpet** [comment]
@rsinghal Thanks I have already seen the code snippet in window.js + documentation but I was on annotation-work branch and it seems our parser for old annotations does not work as expected. I'll fix it :) thanks

**Comment by radpet** [comment]
@rsinghal It should be fixed now

**Pull request merged**
