### PR TITLE
Improve related and seeAlso display

### PR DESCRIPTION
**Pull request by mikeapp**
For #414 .   Renders using `label` if provided, also displays `format` in parentheses next to the link if the format is not HTML.  Tested with examples containing arrays in `related`/`seeAlso` such as the BnF sample manifests and Yale Center for British Art (e.g., http://manifests.britishart.yale.edu/manifest/54267 )
issue-414

### CODE REVIEW

**Comment by azaroth42** [comment]
+1 to displaying format if not HTML.

On Thu, Apr 16, 2015 at 2:19 PM, mikeapp <notifications@github.com> wrote:

> For #414 <https://github.com/IIIF/mirador/issues/414> . Renders using
> label if provided, also displays format in parentheses next to the link
> if the format is not HTML. Tested with examples containing arrays in
> related/seeAlso such as the BnF sample manifests and Yale Center for
> British Art (e.g., http://manifests.britishart.yale.edu/manifest/54267 )
> [image: issue-414]
> <https://cloud.githubusercontent.com/assets/1987952/7191569/a01b4ff0-e45c-11e4-8c5a-2d6f23abd857.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/IIIF/mirador/pull/525
> Commit Summary
>
>    - Fix related and seeAlso display
>
> File Changes
>
>    - *M* js/src/widgets/metadataView.js
>    <https://github.com/IIIF/mirador/pull/525/files#diff-0> (38)
>
> Patch Links:
>
>    - https://github.com/IIIF/mirador/pull/525.patch
>    - https://github.com/IIIF/mirador/pull/525.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/pull/525>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by mikeapp** [comment]
Note that this PR leaves stringifyObject intact to preserve the pretty-printing of other objects/arrays.  I'm not sure where it would actually be useful though, at least with regard to the fields we currently display.   Would `within` ever contain anything other than one or more URIs?   `logo` might be an IIIF resource, but ideally we'd render an image, not pretty-print the data, which is the current behavior.

**Comment by aeschylus** [comment]
Merging this. The prettyPrint does need to go. It's there because we weren't sure what other structures to expect at the time, but we've had further clarification on that now, and in general the metadata panel needs some refactoring/redesign.

See #414

**Comment by aeschylus** [comment]
Looks good.

**Pull request merged**
