### PR TITLE
Manifest thumbnail is read from manifest if available.

### PR DESCRIPTION
**Pull request by hashimmm**
This could be improved so that if the thumbnail URI is an IIIF image service, then a thumbnail of the required size should be requested; but it seems sensible this way too.

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1: to this PR from me! Thanks Hashimmm

**Comment by hashimmm** [comment]
Thanks. I only meant to include one commit. :$ The second one adds description tooltips to the manifest titles in the manifest list panel.

**Comment by aeschylus** [comment]
I would like to merge this, but not with the tooltips. However, I understand why you would want them. In fact, there's a whole issue about it at #287.

**Comment by hashimmm** [comment]
Sure, I made a separate branch and another pull request for this ( #533 ).
Thanks.

**Pull request closed without merging**
